feat: Add driver for Taggun api
jupyter-naas/drivers pull request #196
Opened 2021-11-17 16:05 UTC by justin-prather

Add driver for [taggun](https://taggun.io) receipt/invoice ocr

requires a taggun api key

close #194 

***squash commits on merge***

@FlorentLvr

2021-11-18 10:19 UTC, Dr0p42 requested changes

2021-11-18 10:19 UTC, Dr0p42 commented on naas_drivers/tools/taggun.py
> +    def connect(self, key, file, mode="simple", incognito=False):
Hello @justin-prather why are you passing  a file in the `connect` function? Could it be possible to just pass the `key` (credentials) to this function?

2021-11-18 10:19 UTC, Dr0p42 commented on naas_drivers/tools/taggun.py
> +    def send(self):
I guess  it would be great to pass the file to this function instead

2021-11-20 22:17 UTC, justin-prather commented on naas_drivers/tools/taggun.py
> +    def connect(self, key, file, mode="simple", incognito=False):
I passed it as part of connect so that the filepath could be available for both the hash_file and send functions, but I suppose you're right it could be passed to send instead. i can make this change **👍**

2021-12-02 13:57 UTC, Dr0p42 approved these changes

2021-12-16 09:36 UTC, FlorentLvr approved these changes

2021-12-16 09:39 UTC, merged